### ISSUE TITLE
Add opt-in for polyfills

### ISSUE THREAD

**Issue by captray** [captray/rigby#4]
Might want to allow for a version that includes any necessary polyfills, e.g. Object.assign breaks in IE (shocking).

**Comment by paulirwin** [comment]
I don't know how I feel about taking on dependencies in a library for polyfills. And I vehemently disagree with the idea of ponyfills. What about adding in docs to the readme that tell people to either use the MDN polyfill or require("[es6-object-assign](https://www.npmjs.com/package/es6-object-assign)").polyfill() before they import rigby?

**Comment by captray** [comment]
Not looking to take them on as dependencies. Was considering more of an opt-in, or making them readily available for those that need them. That said, I'm fine with the options you've listed above. It should at least be documented in the readme.
